import { PageHeader } from "@/components/common/page-header";
import { WebhookEventsTable } from "@/features/webhook-management/components/webhook-events-table";

export default function WebhookEventsPage() {
  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Webhook Events"
        description="Monitor events generated by AtMoonPe for merchant integrations."
      />
      <WebhookEventsTable />
    </div>
  );
}
